# Generated by Django 3.1 on 2020-08-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs_app', '0002_auto_20200828_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='current_ticket_process',
            field=models.CharField(choices=[('NEW', 'New'), ('IN PROGRESS', 'In Progress'), ('DONE', 'Done'), ('INVALID', 'Invalid')], default='NEW', max_length=20),
        ),
    ]
