# Generated by Django 3.1 on 2020-08-28 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs_app', '0003_auto_20200828_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='assigned_user',
            new_name='assigned_to',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='completed_user',
            new_name='completed_by',
        ),
    ]
